<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Brianna Meikle">
<meta name="dcterms.date" content="2026-02-28">

<title>Heart Rate During the Mock Audition – K. Gautereaux — Research Archive</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-8a31847d7685a5e2b2f67710c7ed7d92.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">K. Gautereaux — Research Archive</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://kaylagautereaux.com"> 
<span class="menu-text">← kaylagautereaux.com</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../archive/index.html"> 
<span class="menu-text">Archive</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#part-1-individual-session-time-series" id="toc-part-1-individual-session-time-series" class="nav-link active" data-scroll-target="#part-1-individual-session-time-series">Part 1: Individual Session Time Series</a>
  <ul class="collapse">
  <li><a href="#session-1-singer-1-m" id="toc-session-1-singer-1-m" class="nav-link" data-scroll-target="#session-1-singer-1-m">Session 1 — Singer 1 (M)</a></li>
  <li><a href="#session-2-singer-2-f" id="toc-session-2-singer-2-f" class="nav-link" data-scroll-target="#session-2-singer-2-f">Session 2 — Singer 2 (F)</a></li>
  <li><a href="#session-3-singer-3-f" id="toc-session-3-singer-3-f" class="nav-link" data-scroll-target="#session-3-singer-3-f">Session 3 — Singer 3 (F)</a></li>
  <li><a href="#session-4-singer-4-f" id="toc-session-4-singer-4-f" class="nav-link" data-scroll-target="#session-4-singer-4-f">Session 4 — Singer 4 (F)</a></li>
  <li><a href="#session-5-singer-5-m" id="toc-session-5-singer-5-m" class="nav-link" data-scroll-target="#session-5-singer-5-m">Session 5 — Singer 5 (M)</a></li>
  </ul></li>
  <li><a href="#part-2-cross-session-comparisons" id="toc-part-2-cross-session-comparisons" class="nav-link" data-scroll-target="#part-2-cross-session-comparisons">Part 2: Cross-Session Comparisons</a>
  <ul class="collapse">
  <li><a href="#singer-hr-by-audition-phase" id="toc-singer-hr-by-audition-phase" class="nav-link" data-scroll-target="#singer-hr-by-audition-phase">Singer HR by Audition Phase</a></li>
  <li><a href="#singerpanelist-activation-gap" id="toc-singerpanelist-activation-gap" class="nav-link" data-scroll-target="#singerpanelist-activation-gap">Singer–Panelist Activation Gap</a></li>
  <li><a href="#hr-reactivity-profiles" id="toc-hr-reactivity-profiles" class="nav-link" data-scroll-target="#hr-reactivity-profiles">HR Reactivity Profiles</a></li>
  <li><a href="#normalized-hr-trajectories" id="toc-normalized-hr-trajectories" class="nav-link" data-scroll-target="#normalized-hr-trajectories">Normalized HR Trajectories</a></li>
  </ul></li>
  <li><a href="#part-3-same-song-comparisons" id="toc-part-3-same-song-comparisons" class="nav-link" data-scroll-target="#part-3-same-song-comparisons">Part 3: Same-Song Comparisons</a>
  <ul class="collapse">
  <li><a href="#female-singers-if-you-knew-my-story" id="toc-female-singers-if-you-knew-my-story" class="nav-link" data-scroll-target="#female-singers-if-you-knew-my-story">Female Singers — “If You Knew My Story”</a></li>
  <li><a href="#male-singers-shiksa-goddess" id="toc-male-singers-shiksa-goddess" class="nav-link" data-scroll-target="#male-singers-shiksa-goddess">Male Singers — “Shiksa Goddess”</a></li>
  </ul></li>
  <li><a href="#part-4-interpretive-notes" id="toc-part-4-interpretive-notes" class="nav-link" data-scroll-target="#part-4-interpretive-notes">Part 4: Interpretive Notes</a>
  <ul class="collapse">
  <li><a href="#the-singer-4-panelist-3-relationship" id="toc-the-singer-4-panelist-3-relationship" class="nav-link" data-scroll-target="#the-singer-4-panelist-3-relationship">The Singer 4 – Panelist 3 Relationship</a></li>
  <li><a href="#anticipatory-anxiety" id="toc-anticipatory-anxiety" class="nav-link" data-scroll-target="#anticipatory-anxiety">Anticipatory Anxiety</a></li>
  <li><a href="#panelist-anticipatory-activation" id="toc-panelist-anticipatory-activation" class="nav-link" data-scroll-target="#panelist-anticipatory-activation">Panelist Anticipatory Activation</a></li>
  <li><a href="#prepared-vs.-assigned-song" id="toc-prepared-vs.-assigned-song" class="nav-link" data-scroll-target="#prepared-vs.-assigned-song">Prepared vs.&nbsp;Assigned Song</a></li>
  </ul></li>
  <li><a href="#k-mpai-and-maaq-pre-survey-results" id="toc-k-mpai-and-maaq-pre-survey-results" class="nav-link" data-scroll-target="#k-mpai-and-maaq-pre-survey-results">K-MPAI and MAAQ Pre-Survey Results</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a>
  <ul class="collapse">
  <li><a href="#data-pending" id="toc-data-pending" class="nav-link" data-scroll-target="#data-pending">Data Pending</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Heart Rate During the Mock Audition</h1>
  <div class="quarto-categories">
    <div class="quarto-category">performance-anxiety</div>
    <div class="quarto-category">heart-rate</div>
    <div class="quarto-category">descriptive</div>
    <div class="quarto-category">MFA-2026</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Brianna Meikle </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 28, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>This analysis presents the heart rate data from five mock audition sessions. Each singer performed two songs — one prepared, one assigned 24 hours in advance — for a three-person faculty panel. All subjects wore Polar H10 heart rate monitors. HR was recorded at 1 Hz (one value per second) and aligned to audio using a clap-based sync point.</p>
<p><strong>Participants:</strong></p>
<ul>
<li>Singer 1 (S1, M)</li>
<li>Singer 2 (S2, F)</li>
<li>Singer 3 (S3, F)</li>
<li>Singer 4 (S4, F)</li>
<li>Singer 5 (S5, M)</li>
<li>Panelist 1 (F1) — HR data available for all 5 sessions</li>
<li>Panelist 3 (F3) — HR data available for all 5 sessions</li>
</ul>
<p><strong>Assigned pieces:</strong> Female singers (S2, S3, S4): “If You Knew My Story” | Male singers (S1, S5): “Shiksa Goddess”</p>
<p><strong>Data constraint:</strong> HR was exported from Polar Flow at 1 Hz — averaged BPM per second, not beat-to-beat RR intervals. Standard HRV metrics cannot be computed. Analysis focuses on HR magnitude, reactivity, and interpersonal synchrony.</p>
<section id="part-1-individual-session-time-series" class="level2">
<h2 class="anchored" data-anchor-id="part-1-individual-session-time-series">Part 1: Individual Session Time Series</h2>
<p>Each figure shows one audition session with the singer’s HR (red) overlaid with Panelist 1’s HR (purple) and Panelist 3’s HR (blue). Shaded bands indicate audition phases. The x-axis shows elapsed time from the sync clap.</p>
<p><strong>Panelist baseline context:</strong> Panelist 1 runs consistently higher than Panelist 3 across all sessions — typically 98–108 bpm vs.&nbsp;F3’s 75–95 bpm. F1 is also more stable, with less variation across phases. The ~15–20 bpm gap between the two panelists is present in every session, suggesting a stable individual difference in resting autonomic tone rather than a differential response to specific singers.</p>
<section id="session-1-singer-1-m" class="level3">
<h3 class="anchored" data-anchor-id="session-1-singer-1-m">Session 1 — Singer 1 (M)</h3>
<p>Singer 1 begins around 127 bpm and ramps steadily upward through song 1 (prepared piece), reaching peaks near 160 bpm. There is a brief dip during the inter-song gap, followed by a sharp rise into song 2 (assigned piece), where HR reaches its highest sustained values (~155–158 bpm). Panelist 1 holds steady around 100–108 bpm; Panelist 3 remains lower at 85–95 bpm. Both panelists are flat and stable — the singer’s activation gap above the panelist mean is ~50–60 bpm during performance.</p>
</section>
<section id="session-2-singer-2-f" class="level3">
<h3 class="anchored" data-anchor-id="session-2-singer-2-f">Session 2 — Singer 2 (F)</h3>
<p>Singer 2 shows the steepest ramp-up of any singer — HR climbs from ~120 bpm at the start to peak near 169 bpm during song 1 (prepared). HR drops modestly during the inter-song gap (~145 bpm) but rebounds during song 2 (assigned), reaching ~155 bpm. Panelist 1 starts near 108 bpm and drifts down to ~100 bpm during song 1, then rises back toward 105 bpm in the post-session. Panelist 3 hovers lower in the 75–90 bpm range. The activation gap between singer and panelists widens as the session progresses.</p>
</section>
<section id="session-3-singer-3-f" class="level3">
<h3 class="anchored" data-anchor-id="session-3-singer-3-f">Session 3 — Singer 3 (F)</h3>
<p>Singer 3 follows a similar arc to Singer 2 — gradual climb through the pre-singing phase, sustained elevation during song 1 (135–165 bpm), partial recovery in the gap, and a plateau during song 2 (~150–158 bpm). Panelist 1 is steady around 101–107 bpm; Panelist 3 is lower at 80–95 bpm. The inter-song gap shows a brief but noticeable HR spike in Panelist 3’s trace — likely anticipatory activation as the panelist prepares for the next performance (see Panelist Anticipatory Activation below).</p>
</section>
<section id="session-4-singer-4-f" class="level3">
<h3 class="anchored" data-anchor-id="session-4-singer-4-f">Session 4 — Singer 4 (F)</h3>
<p>Singer 4 is a clear outlier. HR starts around 80–90 bpm in the pre-singing phase — within the range typically seen in a <em>panelist</em>, not a singer. During song 1, HR rises modestly to ~105–120 bpm, well below the 140–170 bpm range seen in other singers. During song 2, HR actually <em>drops below baseline</em>, reaching the mid-70s. This is the most visually striking session in the dataset: all three traces (singer, F1, F3) occupy the same vertical range (~75–115 bpm), with frequent crossing and intertwining. Panelist 1 holds around 97–103 bpm but spikes to ~113 bpm during the inter-song gap — the highest F1 variability in any session (sd=5.8). Panelist 3 is similarly variable (sd=8.1 during the gap), at times crossing above the singer’s HR.</p>
<p><strong>Important context:</strong> Panelist 3 had a pre-existing teaching relationship with Singer 4. This likely explains the reduced anxiety response.</p>
</section>
<section id="session-5-singer-5-m" class="level3">
<h3 class="anchored" data-anchor-id="session-5-singer-5-m">Session 5 — Singer 5 (M)</h3>
<p>Singer 5 shows the highest sustained HR of any participant. Starting from a pre-singing baseline of ~135–140 bpm (already elevated), HR climbs rapidly through song 1 to peaks near 184 bpm. The inter-song gap provides minimal recovery (~165 bpm), and song 2 drives HR to its highest sustained values (~170–180 bpm). Panelist 1 stays in the 96–106 bpm range; Panelist 3 is lower at 73–85 bpm. The widest activation gap in the study occurs here — ~80 bpm between singer and panelist mean during song 2.</p>
</section>
</section>
<section id="part-2-cross-session-comparisons" class="level2">
<h2 class="anchored" data-anchor-id="part-2-cross-session-comparisons">Part 2: Cross-Session Comparisons</h2>
<section id="singer-hr-by-audition-phase" class="level3">
<h3 class="anchored" data-anchor-id="singer-hr-by-audition-phase">Singer HR by Audition Phase</h3>
<p>The grouped bar chart below shows each singer’s mean HR (with standard deviation bars) during the four performance phases. The pattern is consistent across four of five singers: HR is lowest during pre-singing, rises sharply for song 1, dips slightly during the inter-song gap, and remains elevated or continues rising into song 2. Singer 4 is the exception — her HR stays in the 88–106 bpm range across all phases, never approaching the 140+ bpm levels seen in the others.</p>
<p><strong>Key observation:</strong> Pre-singing baseline HR is remarkably similar across Singers 1, 2, 3, and 5 (~126–143 bpm), suggesting comparable levels of anticipatory anxiety before singing begins. Singer 4’s pre-singing HR (~91 bpm) is 35–50 bpm lower than the group.</p>
</section>
<section id="singerpanelist-activation-gap" class="level3">
<h3 class="anchored" data-anchor-id="singerpanelist-activation-gap">Singer–Panelist Activation Gap</h3>
<p>The chart below quantifies the HR difference between each singer and the mean of available panelists (Panelist 1 and Panelist 3) for each phase. The gap reflects how far the singer’s autonomic activation exceeds the panelists’ — a rough index of the anxiety asymmetry in the audition relationship.</p>
<p>Singers 1, 2, 3, and 5 show gaps of 30–78 bpm, widening as the session progresses. The gap is largest during the inter-song gap and song 2 for most singers — suggesting that the stress of performing the assigned piece (less familiar, less rehearsed) compounds the already elevated state from song 1.</p>
<p>Singer 4’s gap is negative in most phases — her HR falls <em>below</em> the panelist mean. This is the only singer whose physiological state approximates or drops beneath the panelists’.</p>
</section>
<section id="hr-reactivity-profiles" class="level3">
<h3 class="anchored" data-anchor-id="hr-reactivity-profiles">HR Reactivity Profiles</h3>
<p>The dot-and-line plot below connects each singer’s mean HR across the four phases, making the <em>shape</em> of each stress response visible.</p>
<p>Four distinct profiles emerge:</p>
<ul>
<li><strong>Singer 5</strong> — highest absolute HR, steep climb, no recovery between songs. The most pronounced stress response in the study.</li>
<li><strong>Singer 2</strong> — steep initial climb during song 1, partial recovery in the gap, rebound for song 2. Classic performance anxiety arc.</li>
<li><strong>Singers 1 and 3</strong> — moderate, steady climb. Singer 1 shows the most gradual escalation; Singer 3 plateaus earlier.</li>
<li><strong>Singer 4</strong> — flat trajectory near 90 bpm. Modest rise during song 1, return to baseline for song 2. This profile resembles a panelist more than a performer.</li>
</ul>
</section>
<section id="normalized-hr-trajectories" class="level3">
<h3 class="anchored" data-anchor-id="normalized-hr-trajectories">Normalized HR Trajectories</h3>
<p>All five singers’ HR traces plotted on a common timeline, each zeroed to their own pre-singing baseline mean. This removes differences in resting HR and shows the <em>magnitude of change</em> from baseline — how much each singer’s HR increased due to singing, independent of where they started.</p>
<p>With a 10-second rolling average for readability:</p>
<ul>
<li>Singers 2 and 5 show the largest sustained elevations (~25–40 bpm above baseline).</li>
<li>Singer 1 shows a moderate, steady rise (~15–30 bpm above baseline).</li>
<li>Singer 3 shows a moderate rise with more variability.</li>
<li>Singer 4 shows the smallest reactivity — peaking around +15 bpm during song 1, then <em>dropping below baseline</em> during song 2.</li>
</ul>
</section>
</section>
<section id="part-3-same-song-comparisons" class="level2">
<h2 class="anchored" data-anchor-id="part-3-same-song-comparisons">Part 3: Same-Song Comparisons</h2>
<p>Because the assigned piece was the same within each gender group, we can compare singers’ HR during the identical musical material. Any differences in HR trajectory during the same song reflect individual anxiety responses rather than differences in musical demands.</p>
<section id="female-singers-if-you-knew-my-story" class="level3">
<h3 class="anchored" data-anchor-id="female-singers-if-you-knew-my-story">Female Singers — “If You Knew My Story”</h3>
<p>The figure below shows the three female singers during both their prepared song (left) and the assigned song (right). During the assigned piece — the same 32-bar cut of “If You Knew My Story” — Singers 2 and 3 track closely in the 140–155 bpm range with similar contour, while Singer 4 starts at ~80 bpm and rises slowly to ~99 bpm. The separation between Singer 4 and the other two is even more striking here than during the prepared pieces, because the musical demands are identical.</p>
<p>The three panels below show each female singer (solid line) overlaid with Panelist 1 (dashed purple) and Panelist 3 (dashed blue) during “If You Knew My Story,” aligned to song onset.</p>
<ul>
<li><strong>Singer 2:</strong> Sustained at 140–155 bpm. Panelist 1 holds steady around 98–106 bpm; Panelist 3 rises gently from ~76 to ~89 bpm. The singer sits 40–60 bpm above both panelists throughout.</li>
<li><strong>Singer 3:</strong> Sustained at 140–155 bpm. Panelist 1 is around 98–105 bpm; Panelist 3 stays around 84–88 bpm. Similar gap structure to Singer 2.</li>
<li><strong>Singer 4:</strong> Starts at ~80 bpm — <em>below both panelists</em> (F1 ~98 bpm, F3 ~92 bpm). The singer’s trace rises slowly to ~99 bpm by the end, crossing above Panelist 3 around 15 seconds in but remaining below Panelist 1 for most of the song. This is the only session where the singer’s HR is intertwined with and at times below the panelists’ during active singing.</li>
</ul>
</section>
<section id="male-singers-shiksa-goddess" class="level3">
<h3 class="anchored" data-anchor-id="male-singers-shiksa-goddess">Male Singers — “Shiksa Goddess”</h3>
<p>During the assigned piece “Shiksa Goddess” (right panel), Singer 5 starts at ~166 bpm and climbs to ~180 bpm — a steady upward ramp with no plateau. Singer 1 starts at ~149 bpm and rises gently to ~158 bpm — much flatter. The ~15–20 bpm gap between them is consistent, suggesting a stable difference in stress reactivity rather than a response to a specific musical moment.</p>
<p>Each male singer during “Shiksa Goddess” with panelist overlay:</p>
<ul>
<li><strong>Singer 1:</strong> Flat trace at ~150–158 bpm — almost no variation during the assigned song. Panelist 1 drifts gently from ~110 down to ~104 bpm; Panelist 3 drifts from ~97 to ~89 bpm. The gap between singer and panelist mean (~57 bpm) is stable throughout.</li>
<li><strong>Singer 5:</strong> Climbing trace from ~166 to ~180 bpm. Panelist 1 stays around 99–103 bpm; Panelist 3 drops from ~85 to ~79 bpm. The gap <em>widens</em> over the course of the song — from ~75 bpm at onset to ~90 bpm by the end. Both panelists’ HR either holds flat or decreases while Singer 5’s increases, with Panelist 3 showing the clearest antiphase pattern.</li>
</ul>
</section>
</section>
<section id="part-4-interpretive-notes" class="level2">
<h2 class="anchored" data-anchor-id="part-4-interpretive-notes">Part 4: Interpretive Notes</h2>
<section id="the-singer-4-panelist-3-relationship" class="level3">
<h3 class="anchored" data-anchor-id="the-singer-4-panelist-3-relationship">The Singer 4 – Panelist 3 Relationship</h3>
<p>Singer 4 is a student of Panelist 3 — they have a pre-existing teacher-student relationship. This is an important interpretive lens for several findings:</p>
<ol type="1">
<li><p><strong>Singer 4’s low HR</strong> is consistent with reduced evaluative threat. Performing for one’s own teacher — someone who knows your voice, has heard you at your worst, and is invested in your success — may reduce the sense that resources are insufficient to meet demands (the “threat” state in the biopsychosocial model; Guyon et al., 2020).</p></li>
<li><p><strong>The HR convergence</strong> between Singer 4 and Panelist 3 is consistent with what Coutinho et al.&nbsp;(2021) describe in established relationships. In their study of romantic couples, partners in close relationships showed distinctive physiological synchrony patterns — including in-phase HR coupling (hearts rising and falling together) and antiphase HRV coupling (complementary autonomic regulation). While Singer 4 and Panelist 3 are not romantic partners, the teacher-student bond represents the closest interpersonal relationship of any singer-panelist dyad in this study, and it produces the most convergent physiological profile.</p></li>
<li><p><strong>Both panelists show elevated variability</strong> during Singer 4’s session. Panelist 3’s HR is the most variable of any session (sd=8.1 during the inter-song gap), with traces that cross and intertwine with the singer’s. Panelist 1 also shows its highest inter-song gap variability here (sd=5.8, spiking to ~113 bpm). This suggests the Session 4 was physiologically distinctive for the panelists as well as the singer — though Panelist 3’s response is more pronounced, consistent with the personal investment of evaluating one’s own student.</p></li>
</ol>
<p><strong>For the thesis:</strong> This dyad should be discussed as both a limitation (the teacher-student relationship is a confound that makes Singer 4’s data non-equivalent to the other singers in terms of evaluative stress) and as a case study in co-regulation (the strongest evidence of physiological coupling in the dataset occurs in the dyad with the deepest relational history, consistent with the co-regulation literature).</p>
</section>
<section id="anticipatory-anxiety" class="level3">
<h3 class="anchored" data-anchor-id="anticipatory-anxiety">Anticipatory Anxiety</h3>
<p>Four of five singers show pre-singing HR values of 126–143 bpm — substantially elevated above typical resting heart rate (60–80 bpm for young adults). This is consistent with Vellers et al.&nbsp;(2017), who identified the pre-performance anticipatory period as the most sensitive window for detecting audition stress. The singers are already in a state of sympathetic activation before they begin singing. Singer 4, again, is the exception at ~91 bpm.</p>
</section>
<section id="panelist-anticipatory-activation" class="level3">
<h3 class="anchored" data-anchor-id="panelist-anticipatory-activation">Panelist Anticipatory Activation</h3>
<p>The singer anticipatory anxiety finding has a counterpart on the panelist side. Both Panelist 1 and Panelist 3 show HR ramp-ups in the final seconds of the inter-song gap — before song 2 begins — though the pattern is more consistent in Panelist 3:</p>
<p>Panelist 3 shows anticipatory activation in 4 of 5 sessions; Panelist 1 shows it in 3 of 5. Session 4 produces the strongest ramp in both panelists, reinforcing the interpretation that evaluating Singer 4 — Panelist 3’s own student — carries additional emotional weight for the panel.</p>
<p>This is not a postural artifact — it reflects the anticipatory experience of sitting on a panel. Experienced panelists report feeling a moment of activation as the singer prepares to begin: a mixture of readiness, evaluative engagement, and sometimes empathic nervousness for the performer.</p>
<p>This finding supports the co-regulation framing of the thesis: panelists’ physiology is not inert during the audition. The evaluators respond to the anticipation of the singer’s performance, not just the performance itself. The Session 2 exception (no clear ramp in either panelist) may reflect the unusually long inter-song gap (40 seconds vs.&nbsp;18–25 seconds for other sessions), allowing any anticipatory activation to build and dissipate before song onset.</p>
</section>
<section id="prepared-vs.-assigned-song" class="level3">
<h3 class="anchored" data-anchor-id="prepared-vs.-assigned-song">Prepared vs.&nbsp;Assigned Song</h3>
<p>The data does not show a simple pattern of “assigned piece = more anxiety.” Some singers (1, 3, 5) show higher HR during song 2 (assigned), but Singer 2 shows <em>lower</em> HR during song 2 than song 1. This may reflect:</p>
<ul>
<li>Fatigue or habituation (HR naturally declining after sustained high effort)</li>
<li>The assigned piece being shorter and less demanding than some prepared pieces</li>
<li>Individual differences in how novelty vs.&nbsp;familiarity affects stress</li>
</ul>
<p>The comparison is also confounded by order — song 2 always follows song 1, so any “assigned piece” effect is inseparable from a “second performance” effect. This should be acknowledged as a design limitation.</p>
</section>
</section>
<section id="k-mpai-and-maaq-pre-survey-results" class="level2">
<h2 class="anchored" data-anchor-id="k-mpai-and-maaq-pre-survey-results">K-MPAI and MAAQ Pre-Survey Results</h2>
<p>The K-MPAI was administered to all BoCo BFA/MM voice students as a pre-screening survey. The 5 study participants were drawn from this broader pool of 26 respondents. Scoring follows Kenny (2009): 40 items on a 0–6 scale with 8 reverse-coded positive items (1, 2, 9, 17, 23, 33, 35, 37), range 0–240, clinical threshold 265105.</p>
<p><strong>Population (26 BoCo singer respondents):</strong></p>
<ul>
<li>Mean K-MPAI: 124.1 (SD 31.6), Median: 124.0, Range: 64–185</li>
<li>73% (19/26) score 265105 (clinically significant MPA)</li>
<li>This is a high-anxiety population, consistent with conservatory performance culture</li>
</ul>
<p><strong>Study participants:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 33%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Singer</th>
<th>K-MPAI</th>
<th>Clinical?</th>
<th>MAAQ Flexibility</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>S1 (M)</td>
<td>126</td>
<td>Yes</td>
<td>31</td>
<td>Near population mean</td>
</tr>
<tr class="even">
<td>S2 (F)</td>
<td>111</td>
<td>Yes</td>
<td>35 (highest)</td>
<td>Lowest anxiety, highest flexibility</td>
</tr>
<tr class="odd">
<td>S3 (F)</td>
<td>144</td>
<td>Yes</td>
<td>26</td>
<td>Above population mean</td>
</tr>
<tr class="even">
<td>S4 (F)</td>
<td>159</td>
<td>Yes</td>
<td>21</td>
<td>High anxiety despite lowest HR</td>
</tr>
<tr class="odd">
<td>S5 (M)</td>
<td>174</td>
<td>Yes</td>
<td>17 (lowest)</td>
<td>Highest anxiety, lowest flexibility</td>
</tr>
</tbody>
</table>
<p>All 5 singers score above the clinical threshold — not surprising given they self-selected for a study on performance anxiety. The rank ordering is notable: <strong>Singer 5 (highest K-MPAI, 174) also shows the highest sustained HR in the study, while Singer 2 (lowest K-MPAI, 111) shows the steepest HR ramp-up but also the most recovery between songs.</strong> Singer 4 (K-MPAI 159 — second highest) is the most interesting case: high self-reported anxiety with the <em>lowest</em> physiological response, suggesting that the teacher-student relationship with Panelist 3 may buffer the somatic expression of trait anxiety.</p>
<p><strong>Faculty panelists:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Panelist</th>
<th>K-MPAI</th>
<th>Clinical?</th>
<th>MAAQ Flexibility</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Panelist 1</td>
<td>109 (2 items missing)</td>
<td>Yes</td>
<td>24</td>
</tr>
<tr class="even">
<td>Panelist 2</td>
<td>102</td>
<td>No</td>
<td>33</td>
</tr>
<tr class="odd">
<td>Panelist 3</td>
<td>169</td>
<td>Yes</td>
<td>32</td>
</tr>
</tbody>
</table>
<p>Panelist 3’s K-MPAI (169) is notably high — higher than any study participant except Singer 5. For a panelist whose own performance anxiety is elevated, evaluating singers (especially her own student, Singer 4) may carry additional physiological weight. Panelist 2 falls just below the clinical threshold at 102.</p>
<section id="k-mpai-scoring-note" class="level4">
<h4 class="anchored" data-anchor-id="k-mpai-scoring-note">K-MPAI Scoring Note</h4>
<p>The Qualtrics-generated SC0 score differs from our computed score by a constant of +40 across all 26 respondents (verified: identical SDs, perfect rank correlation). Qualtrics scores the K-MPAI on a 10137 internal scale, while Kenny (2009) specifies 00136. Both apply the same reverse coding on the same 8 items — the only difference is a +1 shift per item across all 40 items (40 0d7 1 = 40). We use the published 00136 convention. The Qualtrics threshold equivalent of 265105 is 265145.</p>
</section>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 6%">
<col style="width: 13%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 26%">
<col style="width: 20%">
<col style="width: 6%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th>Singer</th>
<th>Pre-Singing HR</th>
<th>Song 1 HR</th>
<th>Song 2 HR</th>
<th>Reactivity (Song 1 212 Baseline)</th>
<th>Activation Gap (Song 2)</th>
<th>K-MPAI</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>S1 (M)</td>
<td>128</td>
<td>144</td>
<td>154</td>
<td>+16</td>
<td>+56</td>
<td>126</td>
<td>Steady climber; flattest assigned-song trace</td>
</tr>
<tr class="even">
<td>S2 (F)</td>
<td>128</td>
<td>160</td>
<td>147</td>
<td>+32</td>
<td>+54</td>
<td>111</td>
<td>Steepest ramp-up; HR <em>drops</em> for song 2</td>
</tr>
<tr class="odd">
<td>S3 (F)</td>
<td>126</td>
<td>150</td>
<td>152</td>
<td>+24</td>
<td>+59</td>
<td>144</td>
<td>Moderate, steady; similar to S2 during assigned song</td>
</tr>
<tr class="even">
<td>S4 (F)</td>
<td>91</td>
<td>106</td>
<td>90</td>
<td>+15</td>
<td>2125</td>
<td>159</td>
<td>Outlier — pre-existing relationship with F3; HR <em>below</em> panelist mean</td>
</tr>
<tr class="odd">
<td>S5 (M)</td>
<td>143</td>
<td>167</td>
<td>170</td>
<td>+24</td>
<td>+80</td>
<td>174</td>
<td>Highest absolute HR; no recovery between songs</td>
</tr>
</tbody>
</table>
<p><em>All values are mean HR in bpm. Activation gap = singer mean HR minus mean of Panelist 1 and Panelist 3 during song 2.</em></p>
<section id="data-pending" class="level3">
<h3 class="anchored" data-anchor-id="data-pending">Data Pending</h3>
<ul>
<li><strong>Panelist 2 HR data</strong> is available for Sessions 1–4 (Session 5 still pending export). When the final file arrives, all figures will be updated to incorporate all three panelists.</li>
<li><strong>Post-survey 0d7 HR correlation</strong> — the processed post-survey data has not yet been correlated with HR measures.</li>
<li><strong>K-MPAI 0d7 HR correlation</strong> — the association between trait anxiety scores and physiological reactivity is ready to be tested.</li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/research\.kaylagautereaux\.com");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p><a href="https://kaylagautereaux.com">kaylagautereaux.com</a> · Research Archive</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>