<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Brianna Meikle">
<meta name="dcterms.date" content="2026-02-28">

<title>Heart Rate During the Mock Audition – K. Gautereaux — Research Archive</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-14d69860e42394bc8f238ef95fc5195d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">K. Gautereaux — Research Archive</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://kaylagautereaux.com"> 
<span class="menu-text">← kaylagautereaux.com</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../archive/index.html"> 
<span class="menu-text">Archive</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#part-1-individual-session-time-series" id="toc-part-1-individual-session-time-series" class="nav-link active" data-scroll-target="#part-1-individual-session-time-series">Part 1: Individual Session Time Series</a>
  <ul class="collapse">
  <li><a href="#session-1-014-singer-1-m" id="toc-session-1-014-singer-1-m" class="nav-link" data-scroll-target="#session-1-014-singer-1-m">Session 1 014 Singer 1 (M)</a></li>
  <li><a href="#session-2-014-singer-2-f" id="toc-session-2-014-singer-2-f" class="nav-link" data-scroll-target="#session-2-014-singer-2-f">Session 2 014 Singer 2 (F)</a></li>
  <li><a href="#session-3-014-singer-3-f" id="toc-session-3-014-singer-3-f" class="nav-link" data-scroll-target="#session-3-014-singer-3-f">Session 3 014 Singer 3 (F)</a></li>
  <li><a href="#session-4-014-singer-4-f" id="toc-session-4-014-singer-4-f" class="nav-link" data-scroll-target="#session-4-014-singer-4-f">Session 4 014 Singer 4 (F)</a></li>
  <li><a href="#session-5-014-singer-5-m" id="toc-session-5-014-singer-5-m" class="nav-link" data-scroll-target="#session-5-014-singer-5-m">Session 5 014 Singer 5 (M)</a></li>
  </ul></li>
  <li><a href="#part-2-cross-session-comparisons" id="toc-part-2-cross-session-comparisons" class="nav-link" data-scroll-target="#part-2-cross-session-comparisons">Part 2: Cross-Session Comparisons</a>
  <ul class="collapse">
  <li><a href="#singer-hr-by-audition-phase" id="toc-singer-hr-by-audition-phase" class="nav-link" data-scroll-target="#singer-hr-by-audition-phase">Singer HR by Audition Phase</a></li>
  <li><a href="#singer013panelist-activation-gap" id="toc-singer013panelist-activation-gap" class="nav-link" data-scroll-target="#singer013panelist-activation-gap">Singer013Panelist Activation Gap</a></li>
  <li><a href="#hr-reactivity-profiles" id="toc-hr-reactivity-profiles" class="nav-link" data-scroll-target="#hr-reactivity-profiles">HR Reactivity Profiles</a></li>
  <li><a href="#normalized-hr-trajectories" id="toc-normalized-hr-trajectories" class="nav-link" data-scroll-target="#normalized-hr-trajectories">Normalized HR Trajectories</a></li>
  </ul></li>
  <li><a href="#part-3-same-song-comparisons" id="toc-part-3-same-song-comparisons" class="nav-link" data-scroll-target="#part-3-same-song-comparisons">Part 3: Same-Song Comparisons</a>
  <ul class="collapse">
  <li><a href="#female-singers-014-if-you-knew-my-story" id="toc-female-singers-014-if-you-knew-my-story" class="nav-link" data-scroll-target="#female-singers-014-if-you-knew-my-story">Female Singers 014 "If You Knew My Story"</a></li>
  <li><a href="#male-singers-014-shiksa-goddess" id="toc-male-singers-014-shiksa-goddess" class="nav-link" data-scroll-target="#male-singers-014-shiksa-goddess">Male Singers 014 "Shiksa Goddess"</a></li>
  </ul></li>
  <li><a href="#part-4-interpretive-notes" id="toc-part-4-interpretive-notes" class="nav-link" data-scroll-target="#part-4-interpretive-notes">Part 4: Interpretive Notes</a>
  <ul class="collapse">
  <li><a href="#the-singer-4-013-panelist-3-relationship" id="toc-the-singer-4-013-panelist-3-relationship" class="nav-link" data-scroll-target="#the-singer-4-013-panelist-3-relationship">The Singer 4 013 Panelist 3 Relationship</a></li>
  <li><a href="#anticipatory-anxiety" id="toc-anticipatory-anxiety" class="nav-link" data-scroll-target="#anticipatory-anxiety">Anticipatory Anxiety</a></li>
  <li><a href="#panelist-anticipatory-activation" id="toc-panelist-anticipatory-activation" class="nav-link" data-scroll-target="#panelist-anticipatory-activation">Panelist Anticipatory Activation</a></li>
  <li><a href="#prepared-vs.-assigned-song" id="toc-prepared-vs.-assigned-song" class="nav-link" data-scroll-target="#prepared-vs.-assigned-song">Prepared vs.&nbsp;Assigned Song</a></li>
  </ul></li>
  <li><a href="#k-mpai-and-maaq-pre-survey-results" id="toc-k-mpai-and-maaq-pre-survey-results" class="nav-link" data-scroll-target="#k-mpai-and-maaq-pre-survey-results">K-MPAI and MAAQ Pre-Survey Results</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a>
  <ul class="collapse">
  <li><a href="#data-pending" id="toc-data-pending" class="nav-link" data-scroll-target="#data-pending">Data Pending</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Heart Rate During the Mock Audition</h1>
  <div class="quarto-categories">
    <div class="quarto-category">performance-anxiety</div>
    <div class="quarto-category">heart-rate</div>
    <div class="quarto-category">descriptive</div>
    <div class="quarto-category">MFA-2026</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Brianna Meikle </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 28, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>This analysis presents the heart rate data from five mock audition sessions. Each singer performed two songs — one prepared, one assigned 24 hours in advance — for a three-person faculty panel. All subjects wore Polar H10 heart rate monitors. HR was recorded at 1 Hz (one value per second) and aligned to audio using a clap-based sync point.<strong>Participants:</strong>- Singer 1 (S1, M)- Singer 2 (S2, F)- Singer 3 (S3, F)- Singer 4 (S4, F)- Singer 5 (S5, M)- Panelist 1 (F1) — HR data available for all 5 sessions- Panelist 2 (F2) — HR data available for all 5 sessions- Panelist 3 (F3) — HR data available for all 5 sessions<strong>Assigned pieces:</strong> Female singers (S2, S3, S4): “If You Knew My Story” | Male singers (S1, S5): “Shiksa Goddess”<strong>Data constraint:</strong> HR was exported from Polar Flow at 1 Hz — averaged BPM per second, not beat-to-beat RR intervals. Standard HRV metrics cannot be computed. Analysis focuses on HR magnitude, reactivity, and interpersonal synchrony.<strong>Methodological notes:</strong>- All faculty panelists were seated throughout all auditions. No standing, walking, or postural changes occurred. All panelist HR variations reflect genuine autonomic responses, not movement artifacts.- Panelist 1 wore a facial mask for the duration of the experiment to avoid sharing or receiving illness. This may have contributed slightly to Panelist 1’s elevated baseline HR (~100 bpm), though the consistency across all five sessions suggests a stable individual difference rather than a masking artifact.</p>
<section id="part-1-individual-session-time-series" class="level2">
<h2 class="anchored" data-anchor-id="part-1-individual-session-time-series">Part 1: Individual Session Time Series</h2>
<p>Each figure shows one audition session with the singer’s HR (red) overlaid with Panelist 1 (purple), Panelist 2 (green), and Panelist 3 (blue). Shaded bands indicate audition phases.</p>
<p><strong>Panelist baseline context:</strong> The three panelists — all seated throughout — show a stable hierarchy across all sessions: Panelist 1 runs highest (~98013108 bpm), Panelist 3 is moderate (~7501395 bpm), and Panelist 2 is lowest (~5501365 bpm). Panelist 2’s HR is essentially resting heart rate for a seated adult. These individual differences in resting autonomic tone are consistent across all five sessions, suggesting stable trait-level variation rather than differential responses to specific singers.</p>
<section id="session-1-014-singer-1-m" class="level3">
<h3 class="anchored" data-anchor-id="session-1-014-singer-1-m">Session 1 014 Singer 1 (M)</h3>
<p>Singer 1 begins around 127 bpm and ramps steadily upward through song 1 (prepared piece), reaching peaks near 160 bpm. There is a brief dip during the inter-song gap, followed by a sharp rise into song 2 (assigned piece), where HR reaches its highest sustained values (~155013158 bpm). The three panelists hold flat: Panelist 1 around 100013108 bpm, Panelist 3 at 8501395 bpm, and Panelist 2 near 58 bpm. The singer’s activation gap above the panelist mean is ~6001370 bpm during performance.</p>
</section>
<section id="session-2-014-singer-2-f" class="level3">
<h3 class="anchored" data-anchor-id="session-2-014-singer-2-f">Session 2 014 Singer 2 (F)</h3>
<p>Singer 2 shows the steepest ramp-up of any singer 014 HR climbs from ~120 bpm at the start to peak near 169 bpm during song 1 (prepared). HR drops modestly during the inter-song gap (~145 bpm) but rebounds during song 2 (assigned), reaching ~155 bpm. Panelist 1 drifts from 108 down to ~100 bpm; Panelist 3 hovers in the 7501390 bpm range; Panelist 2 holds steady near 57 bpm. The activation gap widens as the session progresses.</p>
</section>
<section id="session-3-014-singer-3-f" class="level3">
<h3 class="anchored" data-anchor-id="session-3-014-singer-3-f">Session 3 014 Singer 3 (F)</h3>
<p>Singer 3 follows a similar arc to Singer 2 014 gradual climb through the pre-singing phase, sustained elevation during song 1 (135013165 bpm), partial recovery in the gap, and a plateau during song 2 (~150013158 bpm). Panelist 1 is steady around 101013107 bpm; Panelist 3 is at 8001395 bpm; Panelist 2 stays near 5801360 bpm. The inter-song gap shows a brief but noticeable HR spike in Panelist 3’s trace 014 likely anticipatory activation as the panelist prepares for the next performance (see Panelist Anticipatory Activation below).</p>
</section>
<section id="session-4-014-singer-4-f" class="level3">
<h3 class="anchored" data-anchor-id="session-4-014-singer-4-f">Session 4 014 Singer 4 (F)</h3>
<p>Singer 4 is a clear outlier. HR starts around 8001390 bpm in the pre-singing phase 014 within the range typically seen in a <em>panelist</em>, not a singer. During song 1, HR rises modestly to ~105013120 bpm, well below the 140013170 bpm range seen in other singers. During song 2, HR actually <em>drops below baseline</em>, reaching the mid-70s. This is the most visually striking session in the dataset: the singer’s trace overlaps with Panelist 1 and Panelist 3, while Panelist 2 runs below all of them. Panelist 1 spikes to ~113 bpm during the inter-song gap 014 the highest F1 variability in any session (sd=5.8). Panelist 3 is similarly variable (sd=8.1 during the gap).</p>
<p><strong>Important context:</strong> Panelist 3 had a pre-existing teaching relationship with Singer 4. This likely explains the reduced anxiety response.</p>
</section>
<section id="session-5-014-singer-5-m" class="level3">
<h3 class="anchored" data-anchor-id="session-5-014-singer-5-m">Session 5 014 Singer 5 (M)</h3>
<p>Singer 5 shows the highest sustained HR of any participant. Starting from a pre-singing baseline of ~135013140 bpm (already elevated), HR climbs rapidly through song 1 to peaks near 184 bpm. The inter-song gap provides minimal recovery (~165 bpm), and song 2 drives HR to its highest sustained values (~170013180 bpm). The three panelists form a clear floor: Panelist 1 at 96013106 bpm, Panelist 3 at 7301385 bpm, Panelist 2 at 5401359 bpm. The widest activation gap in the study occurs here 014 ~91 bpm between singer and the 3-panelist mean during song 2.</p>
</section>
</section>
<section id="part-2-cross-session-comparisons" class="level2">
<h2 class="anchored" data-anchor-id="part-2-cross-session-comparisons">Part 2: Cross-Session Comparisons</h2>
<section id="singer-hr-by-audition-phase" class="level3">
<h3 class="anchored" data-anchor-id="singer-hr-by-audition-phase">Singer HR by Audition Phase</h3>
<p>The grouped bar chart below shows each singer’s mean HR (with standard deviation bars) during the four performance phases. The pattern is consistent across four of five singers: HR is lowest during pre-singing, rises sharply for song 1, dips slightly during the inter-song gap, and remains elevated or continues rising into song 2. Singer 4 is the exception 014 her HR stays in the 88013106 bpm range across all phases, never approaching the 140+ bpm levels seen in the others.</p>
<p><strong>Key observation:</strong> Pre-singing baseline HR is remarkably similar across Singers 1, 2, 3, and 5 (~126013143 bpm), suggesting comparable levels of anticipatory anxiety before singing begins. Singer 4’s pre-singing HR (~91 bpm) is 3501350 bpm lower than the group.</p>
</section>
<section id="singer013panelist-activation-gap" class="level3">
<h3 class="anchored" data-anchor-id="singer013panelist-activation-gap">Singer013Panelist Activation Gap</h3>
<p>The chart below quantifies the HR difference between each singer and the mean of all three panelists for each phase. The gap reflects how far the singer’s autonomic activation exceeds the panelists’ 014 a rough index of the anxiety asymmetry in the audition relationship. With Panelist 2 included (mean HR ~58 bpm, seated), the 3-panelist average is lower than the earlier 2-panelist estimate, so activation gaps are wider.</p>
<p>Singers 1, 2, 3, and 5 show gaps of 3801391 bpm, widening as the session progresses. The gap is largest during the inter-song gap and song 2 for most singers 014 suggesting that the stress of performing the assigned piece (less familiar, less rehearsed) compounds the already elevated state from song 1.</p>
<p>Singer 4’s gap is small but positive (+8 bpm during song 2) 014 her HR stays close to the panelist range. This is the only singer whose physiological state approximates the panelists’.</p>
</section>
<section id="hr-reactivity-profiles" class="level3">
<h3 class="anchored" data-anchor-id="hr-reactivity-profiles">HR Reactivity Profiles</h3>
<p>The dot-and-line plot below connects each singer’s mean HR across the four phases, making the <em>shape</em> of each stress response visible.</p>
<p>Four distinct profiles emerge:</p>
<ul>
<li><strong>Singer 5</strong> 014 highest absolute HR, steep climb, no recovery between songs. The most pronounced stress response in the study.</li>
<li><strong>Singer 2</strong> 014 steep initial climb during song 1, partial recovery in the gap, rebound for song 2. Classic performance anxiety arc.</li>
<li><strong>Singers 1 and 3</strong> 014 moderate, steady climb. Singer 1 shows the most gradual escalation; Singer 3 plateaus earlier.</li>
<li><strong>Singer 4</strong> 014 flat trajectory near 90 bpm. Modest rise during song 1, return to baseline for song 2. This profile resembles a panelist more than a performer.</li>
</ul>
</section>
<section id="normalized-hr-trajectories" class="level3">
<h3 class="anchored" data-anchor-id="normalized-hr-trajectories">Normalized HR Trajectories</h3>
<p>All five singers’ HR traces plotted on a common timeline, each zeroed to their own pre-singing baseline mean. This removes differences in resting HR and shows the <em>magnitude of change</em> from baseline.</p>
<p>With a 10-second rolling average for readability:</p>
<ul>
<li>Singers 2 and 5 show the largest sustained elevations (~2501340 bpm above baseline).</li>
<li>Singer 1 shows a moderate, steady rise (~1501330 bpm above baseline).</li>
<li>Singer 3 shows a moderate rise with more variability.</li>
<li>Singer 4 shows the smallest reactivity 014 peaking around +15 bpm during song 1, then <em>dropping below baseline</em> during song 2.</li>
</ul>
</section>
</section>
<section id="part-3-same-song-comparisons" class="level2">
<h2 class="anchored" data-anchor-id="part-3-same-song-comparisons">Part 3: Same-Song Comparisons</h2>
<p>Because the assigned piece was the same within each gender group, we can compare singers’ HR during the identical musical material. Any differences in HR trajectory during the same song reflect individual anxiety responses rather than differences in musical demands.</p>
<section id="female-singers-014-if-you-knew-my-story" class="level3">
<h3 class="anchored" data-anchor-id="female-singers-014-if-you-knew-my-story">Female Singers 014 "If You Knew My Story"</h3>
<p>During the assigned piece (right panel) 014 the same 32-bar cut 014 Singers 2 and 3 track closely in the 140013155 bpm range with similar contour, while Singer 4 starts at ~80 bpm and rises slowly to ~99 bpm. The separation between Singer 4 and the other two is even more striking here than during the prepared pieces, because the musical demands are identical.</p>
<p>Each female singer during "If You Knew My Story" with all three panelists overlaid:</p>
<ul>
<li><strong>Singer 2:</strong> Sustained at 140013155 bpm. All three panelists hold flat below, with Panelist 2 running lowest (~57 bpm). The singer sits 4001380+ bpm above the panelist range.</li>
<li><strong>Singer 3:</strong> Similar profile to Singer 2. Panelist traces are stable and well below.</li>
<li><strong>Singer 4:</strong> Starts at ~80 bpm 014 <em>below Panelist 1</em> (~98 bpm) and near Panelist 3 (~92 bpm). Only Panelist 2 (~56 bpm) is consistently below her. This is the only session where the singer’s HR is intertwined with the panelists’ during active singing.</li>
</ul>
</section>
<section id="male-singers-014-shiksa-goddess" class="level3">
<h3 class="anchored" data-anchor-id="male-singers-014-shiksa-goddess">Male Singers 014 "Shiksa Goddess"</h3>
<p>During the assigned piece (right panel), Singer 5 starts at ~166 bpm and climbs to ~180 bpm. Singer 1 starts at ~149 bpm and rises gently to ~158 bpm. The ~1501320 bpm gap between them is consistent, suggesting a stable difference in stress reactivity rather than a response to a specific musical moment.</p>
<p>Each male singer during "Shiksa Goddess" with all three panelists:</p>
<ul>
<li><strong>Singer 1:</strong> Flat trace at ~150013158 bpm. All three panelists well below. The gap between singer and 3-panelist mean (~70 bpm) is stable throughout.</li>
<li><strong>Singer 5:</strong> Climbing trace from ~166 to ~180 bpm. The gap <em>widens</em> over the course of the song 014 panelists hold flat or decrease while Singer 5 continues climbing. Panelist 3 shows the clearest antiphase pattern (HR decreasing as singer’s increases).</li>
</ul>
</section>
</section>
<section id="part-4-interpretive-notes" class="level2">
<h2 class="anchored" data-anchor-id="part-4-interpretive-notes">Part 4: Interpretive Notes</h2>
<section id="the-singer-4-013-panelist-3-relationship" class="level3">
<h3 class="anchored" data-anchor-id="the-singer-4-013-panelist-3-relationship">The Singer 4 013 Panelist 3 Relationship</h3>
<p>Singer 4 is a student of Panelist 3 014 they have a pre-existing teacher-student relationship. This is an important interpretive lens for several findings:</p>
<ol type="1">
<li><p><strong>Singer 4’s low HR</strong> is consistent with reduced evaluative threat. Performing for one’s own teacher 014 someone who knows your voice, has heard you at your worst, and is invested in your success 014 may reduce the sense that resources are insufficient to meet demands (the "threat" state in the biopsychosocial model; Guyon et al., 2020).</p></li>
<li><p><strong>The HR convergence</strong> between Singer 4 and Panelist 3 is consistent with what Coutinho et al.&nbsp;(2021) describe in established relationships. In their study of romantic couples, partners in close relationships showed distinctive physiological synchrony patterns 014 including in-phase HR coupling. While Singer 4 and Panelist 3 are not romantic partners, the teacher-student bond represents the closest interpersonal relationship of any singer-panelist dyad in this study, and it produces the most convergent physiological profile.</p></li>
<li><p><strong>All three panelists show elevated variability</strong> during Singer 4’s session. Panelist 3’s HR is the most variable of any session (sd=8.1 during the inter-song gap). Panelist 1 also shows its highest variability here (sd=5.8, spiking to ~113 bpm). Even Panelist 2, typically the most stable, shows slightly more variation. This suggests Session 4 was physiologically distinctive for the entire panel.</p></li>
</ol>
<p><strong>For the thesis:</strong> This dyad should be discussed as both a limitation (the teacher-student relationship is a confound that makes Singer 4’s data non-equivalent to the other singers in terms of evaluative stress) and as a case study in co-regulation (the strongest evidence of physiological coupling in the dataset occurs in the dyad with the deepest relational history).</p>
</section>
<section id="anticipatory-anxiety" class="level3">
<h3 class="anchored" data-anchor-id="anticipatory-anxiety">Anticipatory Anxiety</h3>
<p>Four of five singers show pre-singing HR values of 126013143 bpm 014 substantially elevated above typical resting heart rate (6001380 bpm for young adults). This is consistent with Vellers et al.&nbsp;(2017), who identified the pre-performance anticipatory period as the most sensitive window for detecting audition stress. The singers are already in a state of sympathetic activation before they begin singing. Singer 4, again, is the exception at ~91 bpm.</p>
</section>
<section id="panelist-anticipatory-activation" class="level3">
<h3 class="anchored" data-anchor-id="panelist-anticipatory-activation">Panelist Anticipatory Activation</h3>
<p>The singer anticipatory anxiety finding has a counterpart on the panelist side. All three panelists 014 seated throughout 014 show HR ramp-ups in the final seconds of the inter-song gap before song 2 begins. Because the panelists did not stand, shift position, or move during the auditions, these HR changes cannot be attributed to postural artifacts. They reflect genuine autonomic activation 014 the evaluative experience of preparing to hear the next piece.</p>
<p>Panelist 3 shows the most consistent pattern (anticipatory activation in 4 of 5 sessions), with Session 4 (her own student) producing the largest ramp (+17.7 bpm). Panelist 1 shows activation in 3 of 5 sessions. Panelist 2, with the lowest overall HR, shows modest changes that are harder to distinguish from baseline fluctuation.</p>
</section>
<section id="prepared-vs.-assigned-song" class="level3">
<h3 class="anchored" data-anchor-id="prepared-vs.-assigned-song">Prepared vs.&nbsp;Assigned Song</h3>
<p>The data does not show a simple pattern of "assigned piece = more anxiety." Some singers (1, 3, 5) show higher HR during song 2 (assigned), but Singer 2 shows <em>lower</em> HR during song 2 than song 1. This may reflect:</p>
<ul>
<li>Fatigue or habituation (HR naturally declining after sustained high effort)</li>
<li>The assigned piece being shorter and less demanding than some prepared pieces</li>
<li>Individual differences in how novelty vs.&nbsp;familiarity affects stress</li>
</ul>
<p>The comparison is also confounded by order 014 song 2 always follows song 1, so any "assigned piece" effect is inseparable from a "second performance" effect. This should be acknowledged as a design limitation.</p>
</section>
</section>
<section id="k-mpai-and-maaq-pre-survey-results" class="level2">
<h2 class="anchored" data-anchor-id="k-mpai-and-maaq-pre-survey-results">K-MPAI and MAAQ Pre-Survey Results</h2>
<p>The K-MPAI was administered to all BoCo BFA/MM voice students as a pre-screening survey. The 5 study participants were drawn from this broader pool of 26 respondents. Scoring follows Kenny (2009): 40 items on a 00136 scale with 8 reverse-coded positive items (1, 2, 9, 17, 23, 33, 35, 37), range 0013240, clinical threshold 265105.</p>
<p><strong>Population (26 BoCo singer respondents):</strong></p>
<ul>
<li>Mean K-MPAI: 124.1 (SD 31.6), Median: 124.0, Range: 64013185</li>
<li>73% (19/26) score 265105 (clinically significant MPA)</li>
<li>This is a high-anxiety population, consistent with conservatory performance culture</li>
</ul>
<p><strong>Study participants:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 33%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Singer</th>
<th>K-MPAI</th>
<th>Clinical?</th>
<th>MAAQ Flexibility</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>S1 (M)</td>
<td>126</td>
<td>Yes</td>
<td>31</td>
<td>Near population mean</td>
</tr>
<tr class="even">
<td>S2 (F)</td>
<td>111</td>
<td>Yes</td>
<td>35 (highest)</td>
<td>Lowest anxiety, highest flexibility</td>
</tr>
<tr class="odd">
<td>S3 (F)</td>
<td>144</td>
<td>Yes</td>
<td>26</td>
<td>Above population mean</td>
</tr>
<tr class="even">
<td>S4 (F)</td>
<td>159</td>
<td>Yes</td>
<td>21</td>
<td>High anxiety despite lowest HR</td>
</tr>
<tr class="odd">
<td>S5 (M)</td>
<td>174</td>
<td>Yes</td>
<td>17 (lowest)</td>
<td>Highest anxiety, lowest flexibility</td>
</tr>
</tbody>
</table>
<p>All 5 singers score above the clinical threshold 014 not surprising given they self-selected for a study on performance anxiety. The rank ordering is notable: <strong>Singer 5 (highest K-MPAI, 174) also shows the highest sustained HR in the study, while Singer 2 (lowest K-MPAI, 111) shows the steepest HR ramp-up but also the most recovery between songs.</strong> Singer 4 (K-MPAI 159 014 second highest) is the most interesting case: high self-reported anxiety with the <em>lowest</em> physiological response, suggesting that the teacher-student relationship with Panelist 3 may buffer the somatic expression of trait anxiety.</p>
<p><strong>Faculty panelists:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Panelist</th>
<th>K-MPAI</th>
<th>Clinical?</th>
<th>MAAQ Flexibility</th>
<th>Mean HR (seated)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Panelist 1</td>
<td>109 (2 items missing)</td>
<td>Yes</td>
<td>24</td>
<td>~101 bpm</td>
</tr>
<tr class="even">
<td>Panelist 2</td>
<td>102</td>
<td>No</td>
<td>33</td>
<td>~58 bpm</td>
</tr>
<tr class="odd">
<td>Panelist 3</td>
<td>169</td>
<td>Yes</td>
<td>32</td>
<td>~85 bpm</td>
</tr>
</tbody>
</table>
<p>Panelist 3’s K-MPAI (169) is notably high 014 higher than any study participant except Singer 5. For a panelist whose own performance anxiety is elevated, evaluating singers (especially her own student, Singer 4) may carry additional physiological weight. Panelist 2 falls just below the clinical threshold at 102 and shows the lowest HR of anyone in the study 014 essentially resting heart rate while seated. The K-MPAI ranking on the faculty side (F3 &gt; F1 &gt; F2) does not map directly to their HR ranking (F1 &gt; F3 &gt; F2), but Panelist 2 being the calmest on both measures is consistent.</p>
<section id="k-mpai-scoring-note" class="level4">
<h4 class="anchored" data-anchor-id="k-mpai-scoring-note">K-MPAI Scoring Note</h4>
<p>The Qualtrics-generated SC0 score differs from our computed score by a constant of +40 across all 26 respondents (verified: identical SDs, perfect rank correlation). Qualtrics scores the K-MPAI on a 10137 internal scale, while Kenny (2009) specifies 00136. Both apply the same reverse coding on the same 8 items 014 the only difference is a +1 shift per item across all 40 items (40 0d7 1 = 40). We use the published 00136 convention. The Qualtrics threshold equivalent of 265105 is 265145.</p>
</section>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 6%">
<col style="width: 13%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 26%">
<col style="width: 20%">
<col style="width: 6%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th>Singer</th>
<th>Pre-Singing HR</th>
<th>Song 1 HR</th>
<th>Song 2 HR</th>
<th>Reactivity (Song 1 212 Baseline)</th>
<th>Activation Gap (Song 2)</th>
<th>K-MPAI</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>S1 (M)</td>
<td>128</td>
<td>144</td>
<td>154</td>
<td>+16</td>
<td>+70</td>
<td>126</td>
<td>Steady climber; flattest assigned-song trace</td>
</tr>
<tr class="even">
<td>S2 (F)</td>
<td>128</td>
<td>160</td>
<td>147</td>
<td>+32</td>
<td>+66</td>
<td>111</td>
<td>Steepest ramp-up; HR <em>drops</em> for song 2</td>
</tr>
<tr class="odd">
<td>S3 (F)</td>
<td>126</td>
<td>150</td>
<td>152</td>
<td>+24</td>
<td>+70</td>
<td>144</td>
<td>Moderate, steady; similar to S2 during assigned song</td>
</tr>
<tr class="even">
<td>S4 (F)</td>
<td>91</td>
<td>106</td>
<td>90</td>
<td>+15</td>
<td>+8</td>
<td>159</td>
<td>Outlier 014 pre-existing relationship with F3; HR near panelist range</td>
</tr>
<tr class="odd">
<td>S5 (M)</td>
<td>143</td>
<td>167</td>
<td>170</td>
<td>+24</td>
<td>+91</td>
<td>174</td>
<td>Highest absolute HR; no recovery between songs</td>
</tr>
</tbody>
</table>
<p><em>All values are mean HR in bpm. Activation gap = singer mean HR minus mean of all three panelists during song 2.</em></p>
<section id="data-pending" class="level3">
<h3 class="anchored" data-anchor-id="data-pending">Data Pending</h3>
<ul>
<li><strong>Post-survey 0d7 HR correlation</strong> 014 the processed post-survey data has not yet been correlated with HR measures.</li>
<li><strong>K-MPAI 0d7 HR correlation</strong> 014 the association between trait anxiety scores and physiological reactivity is ready to be tested.</li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/research\.kaylagautereaux\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p><a href="https://kaylagautereaux.com">kaylagautereaux.com</a> · Research Archive</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>